[workspace]
authors = ["Anthony J. Clark <anthonyjclark@gmail.com>"]
channels = ["conda-forge"]
name = "sapien-robot"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pytorch-gpu = ">=1.11.0,<2"
torchvision = ">=0.12.0,<0.13"

[pypi-dependencies]
mani-skill = "~=3.0.0b21"